;;; opencode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list (quote load-path) (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from opencode.el

(defvar opencode-mode nil "\
Non-nil if Opencode mode is enabled.
See the `opencode-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `opencode-mode'.")
(custom-autoload 'opencode-mode "opencode" nil)
(autoload 'opencode-mode "opencode" "\
Global minor mode for the OpenCode AI coding agent.

When enabled, provides the `C-c o' prefix keymap and modeline indicator.

\\{opencode-mode-map}

This is a global minor mode.  If called interactively, toggle the
`Opencode mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='opencode-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'opencode-start "opencode" "\
Start the OpenCode server and connect.
DIRECTORY is the project directory.  When nil, the resolution order is:
  1. `opencode-default-directory' (if set)
  2. Project root via `project-current' (detects .git, .hg, etc.)
  3. `default-directory' of the current buffer
When called interactively with a prefix argument, prompts for the directory.

(fn &optional DIRECTORY)" t)
(autoload 'opencode-attach "opencode" "\
Attach to an already-running OpenCode server at URL.
Unlike `opencode-start', this never spawns a subprocess.
URL can be:
  - A full URL: \"http://remote-host:4096\"
  - host:port:  \"remote-host:4096\"
  - Just a port: \"4096\"
DIRECTORY is the project directory (same resolution as `opencode-start').
Interactively, prompts for URL; with prefix arg also prompts for DIRECTORY.

(fn URL &optional DIRECTORY)" t)
(autoload 'opencode-chat "opencode" "\
Open a chat buffer for SESSION-ID.
If SESSION-ID is nil, prompts for a session from the list.
The completion list includes a \"★ New session\" option at the top.
Auto-connects to the server if `opencode-server-port' is set.
The session list is scoped to the current buffer's project (via
`project-current'), so switching projects shows the right sessions.

(fn &optional SESSION-ID)" t)
(autoload 'opencode-list-sessions "opencode" "\
Open the session list buffer for the current project." t)
(autoload 'opencode-new-session "opencode" "\
Create a new session with optional TITLE and open it.

(fn &optional TITLE)" t)
(autoload 'opencode-abort "opencode" "\
Abort the current generation in the active chat buffer." t)
(autoload 'opencode-toggle-sidebar "opencode" "\
Toggle the OpenCode session sidebar." t)
(autoload 'opencode-disconnect "opencode" "\
Disconnect from the OpenCode server and stop the subprocess." t)
(autoload 'opencode-refresh "opencode" "\
Refresh all cached data from the server.
Invalidates agent, config, and command caches, re-fetches everything,
and schedules a refresh for all open chat and sidebar buffers.
Same behavior as `server.instance.disposed'." t)
(register-definition-prefixes "opencode" '("opencode-"))


;;; Generated autoloads from opencode-agent.el

(register-definition-prefixes "opencode-agent" '("opencode-agent-"))


;;; Generated autoloads from opencode-api.el

(register-definition-prefixes "opencode-api" '("opencode-"))


;;; Generated autoloads from opencode-chat.el

(defvar opencode-chat-user-keymap (make-sparse-keymap) "\
Public parent keymap for all `opencode-chat-mode' keymaps.
Installed as the parent of `opencode-chat-mode-map',
`opencode-chat-message-map', and `opencode-chat-input-map' when
`opencode-chat' is loaded.  Bindings added here propagate to all three
regions.  Combine with `opencode-chat-unbound-keys' to override package
defaults.  See `opencode-chat.el' for full documentation.

Autoloaded so users can `keymap-set' into this variable from init
files before `opencode-chat' has been loaded.")
(defvar opencode-chat-unbound-keys nil "\
Keys to unbind from every internal `opencode-chat-mode' keymap.
A list of key descriptions accepted by `keymap-set'.  See
`opencode-chat.el' for full documentation.

Autoloaded so users can set this via `setq', `setopt', or
`customize-set-variable' from init files before `opencode-chat' has
been loaded; the apply pass runs on first `opencode-chat-mode' invocation.")
(custom-autoload 'opencode-chat-unbound-keys "opencode-chat" nil)
(register-definition-prefixes "opencode-chat" '("opencode-chat-"))


;;; Generated autoloads from opencode-config.el

(register-definition-prefixes "opencode-config" '("opencode-config-"))


;;; Generated autoloads from opencode-diff.el

(register-definition-prefixes "opencode-diff" '("opencode-diff-"))


;;; Generated autoloads from opencode-log.el

(register-definition-prefixes "opencode-log" '("opencode-"))


;;; Generated autoloads from opencode-markdown.el

(register-definition-prefixes "opencode-markdown" '("opencode-markdown-"))


;;; Generated autoloads from opencode-permission.el

(register-definition-prefixes "opencode-permission" '("opencode-permission-"))


;;; Generated autoloads from opencode-popup.el

(register-definition-prefixes "opencode-popup" '("opencode-popup--"))


;;; Generated autoloads from opencode-question.el

(register-definition-prefixes "opencode-question" '("opencode-question-"))


;;; Generated autoloads from opencode-status.el

(autoload 'opencode-server-status "opencode-status" "\
Show server status popup (MCP, LSP, Formatter)." t)

(register-definition-prefixes "opencode-status" '("opencode-status-"))


;;; Generated autoloads from opencode-server.el

(register-definition-prefixes "opencode-server" '("opencode-server-"))


;;; Generated autoloads from opencode-session.el

(register-definition-prefixes "opencode-session" '("opencode-session-"))


;;; Generated autoloads from opencode-sidebar.el

(register-definition-prefixes "opencode-sidebar" '("opencode-sidebar-"))


;;; Generated autoloads from opencode-sse.el

(register-definition-prefixes "opencode-sse" '("opencode-sse-"))


;;; Generated autoloads from opencode-todo.el

(register-definition-prefixes "opencode-todo" '("opencode-todo-"))


;;; Generated autoloads from opencode-window.el

(register-definition-prefixes "opencode-window" '("opencode-"))


;;; Generated autoloads from opencode-util.el

(register-definition-prefixes "opencode-util" '("opencode-"))


;;; Generated autoloads from opencode-command.el

(autoload 'opencode-command-select "opencode-command" "\
Select and execute an OpenCode local command via `completing-read'.
Presents a list of client-side built-in commands (e.g. /compact, /rename)
and executes the selected one.

Must be called from an `opencode-chat-mode' buffer." t)
(autoload 'opencode-command-select-global "opencode-command" "\
Select and execute an OpenCode command, creating a session if needed.
If not in a chat buffer, creates a new session first." t)
(register-definition-prefixes "opencode-command" '("opencode-command--"))


;;; Generated autoloads from opencode-chat-input.el

(register-definition-prefixes "opencode-chat-input" '("opencode-chat-"))


;;; Generated autoloads from opencode-chat-message.el

(register-definition-prefixes "opencode-chat-message" '("opencode-chat-"))


;;; Generated autoloads from opencode-chat-state.el

(register-definition-prefixes "opencode-chat-state" '("opencode-chat--"))


;;; Generated autoloads from opencode-api-cache.el

(register-definition-prefixes "opencode-api-cache" '("opencode-"))

;;; End of scraped data

(provide 'opencode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; opencode-autoloads.el ends here
