;;; opencode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list (quote load-path) (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from opencode.el

(defvar opencode-mode nil "\
Non-nil if Opencode mode is enabled.
See the `opencode-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `opencode-mode'.")
(custom-autoload 'opencode-mode "opencode" nil)
(autoload 'opencode-mode "opencode" "\
Global minor mode for OpenCode and Pi AI coding agents.

When enabled, provides the `C-c o' prefix keymap and modeline indicator.

\\{opencode-mode-map}

This is a global minor mode.  If called interactively, toggle the
`Opencode mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='opencode-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'opencode-start "opencode" "\
Start the OpenCode server and connect.
DIRECTORY is the project directory.  When nil, the resolution order is:
  1. `opencode-default-directory' (if set)
  2. Project root via `project-current' (detects .git, .hg, etc.)
  3. `default-directory' of the current buffer
When called interactively with a prefix argument, prompts for the directory.

(fn &optional DIRECTORY)" t)
(autoload 'opencode-attach "opencode" "\
Attach to an already-running OpenCode server at URL.
Unlike `opencode-start', this never spawns a subprocess.
URL can be:
  - A full URL: \"http://remote-host:4096\"
  - host:port:  \"remote-host:4096\"
  - Just a port: \"4096\"
DIRECTORY is the project directory (same resolution as `opencode-start').
Interactively, prompts for URL; with prefix arg also prompts for DIRECTORY.

(fn URL &optional DIRECTORY)" t)
(autoload 'opencode-chat "opencode" "\
Open a chat buffer for SESSION-ID using BACKEND in DIRECTORY.
If SESSION-ID is nil, prompts for a session.
The completion list includes a \"★ New session\" option at the top.
Auto-connects to the server if `opencode-server-port' is set.
When DIRECTORY is nil, the picker is scoped to the current buffer's
project via `project-current', so switching projects shows the right
sessions.  BACKEND defaults to `opencode-backend-current'.

(fn &optional SESSION-ID BACKEND DIRECTORY)" t)
(autoload 'opencode-new-session "opencode" "\
Create a new session with optional TITLE and open it.
BACKEND defaults to `opencode-backend-current'.

(fn &optional TITLE BACKEND)" t)
(autoload 'opencode-abort "opencode" "\
Abort the current generation in the active chat buffer." t)
(autoload 'opencode-toggle-sidebar "opencode" "\
Toggle the OpenCode session sidebar." t)
(autoload 'opencode-disconnect "opencode" "\
Disconnect from the OpenCode server and stop the subprocess." t)
(autoload 'opencode-refresh "opencode" "\
Refresh all cached OpenCode data from the server.
Invalidates OpenCode agent, config, and command caches, re-fetches
everything, and schedules a refresh for all open chat and sidebar buffers.
Same behavior as `server.instance.disposed'." t)
(register-definition-prefixes "opencode" '("opencode-"))


;;; Generated autoloads from opencode-agent.el

(register-definition-prefixes "opencode-agent" '("opencode-agent-"))


;;; Generated autoloads from opencode-api.el

(register-definition-prefixes "opencode-api" '("opencode-api-"))


;;; Generated autoloads from opencode-chat.el

(register-definition-prefixes "opencode-chat" '("opencode-chat-"))


;;; Generated autoloads from opencode-config.el

(register-definition-prefixes "opencode-config" '("opencode-config-"))


;;; Generated autoloads from opencode-diff.el

(register-definition-prefixes "opencode-diff" '("opencode-diff-"))


;;; Generated autoloads from opencode-log.el

(register-definition-prefixes "opencode-log" '("opencode-"))


;;; Generated autoloads from opencode-markdown.el

(register-definition-prefixes "opencode-markdown" '("opencode-markdown-"))


;;; Generated autoloads from opencode-permission.el

(register-definition-prefixes "opencode-permission" '("opencode-permission-"))


;;; Generated autoloads from opencode-popup.el

(register-definition-prefixes "opencode-popup" '("opencode-popup--"))


;;; Generated autoloads from opencode-question.el

(register-definition-prefixes "opencode-question" '("opencode-question-"))


;;; Generated autoloads from opencode-status.el

(autoload 'opencode-server-status "opencode-status" "\
Show server status popup (MCP, LSP, Formatter)." t)
(register-definition-prefixes "opencode-status" '("opencode-status-"))


;;; Generated autoloads from opencode-session.el

(register-definition-prefixes "opencode-session" '("opencode-session-"))


;;; Generated autoloads from opencode-sidebar.el

(register-definition-prefixes "opencode-sidebar" '("opencode-sidebar-"))


;;; Generated autoloads from opencode-sse.el

(register-definition-prefixes "opencode-sse" '("opencode-sse-"))


;;; Generated autoloads from opencode-todo.el

(register-definition-prefixes "opencode-todo" '("opencode-todo-"))


;;; Generated autoloads from opencode-window.el

(register-definition-prefixes "opencode-window" '("opencode-"))


;;; Generated autoloads from opencode-util.el

(register-definition-prefixes "opencode-util" '("opencode-"))


;;; Generated autoloads from opencode-command.el

(autoload 'opencode-command-select "opencode-command" "\
Select and execute an OpenCode local command via `completing-read'.
Presents a list of client-side built-in commands (e.g. /compact, /rename)
and executes the selected one.

Must be called from an `opencode-chat-mode' buffer." t)
(autoload 'opencode-command-select-global "opencode-command" "\
Select and execute an OpenCode command, creating a session if needed.
If not in a chat buffer, creates a new session first." t)
(register-definition-prefixes "opencode-command" '("opencode-command-"))


;;; Generated autoloads from opencode-chat-input.el

(register-definition-prefixes "opencode-chat-input" '("opencode-chat-"))


;;; Generated autoloads from opencode-chat-message.el

(register-definition-prefixes "opencode-chat-message" '("opencode-chat-"))


;;; Generated autoloads from opencode-chat-state.el

(register-definition-prefixes "opencode-chat-state" '("opencode-chat-"))


;;; Generated autoloads from opencode-api-cache.el

(register-definition-prefixes "opencode-api-cache" '("opencode-"))


;;; Generated autoloads from opencode-chat-resolve.el

(register-definition-prefixes "opencode-chat-resolve" '("opencode-chat--resolve-defaults"))


;;; Generated autoloads from opencode-domain.el

(register-definition-prefixes "opencode-domain" '("opencode-domain-"))


;;; Generated autoloads from opencode-event.el

(register-definition-prefixes "opencode-event" '("opencode-"))


;;; Generated autoloads from opencode-tool-render.el

(register-definition-prefixes "opencode-tool-render" '("opencode-chat-"))


;;; Generated autoloads from opencode-ui.el

(register-definition-prefixes "opencode-ui" '("opencode-ui--"))


;;; Generated autoloads from opencode-backend.el

(register-definition-prefixes "opencode-backend" '("opencode-backend-"))


;;; Generated autoloads from opencode-lifecycle.el

(register-definition-prefixes "opencode-lifecycle" '("opencode-lifecycle-"))


;;; Generated autoloads from opencode-pi.el

(autoload 'opencode-pi "opencode-pi" "\
Start or resume a Pi coding-agent session and open a chat buffer.
DIRECTORY is the project root (defaults to the current project or
`default-directory').  Offers existing on-disk sessions plus a \"New
session\" option.  Spawns `pi --mode rpc' (resuming the chosen session
file when applicable), learns the Pi session id, wires event and UI
handlers, then opens the chat buffer bound to the `pi' backend.

(fn &optional DIRECTORY)" t)
(register-definition-prefixes "opencode-pi" '("opencode-pi-"))


;;; Generated autoloads from opencode-pi-rpc.el

(register-definition-prefixes "opencode-pi-rpc" '("opencode-pi-"))


;;; Generated autoloads from opencode-pi-widget.el

(register-definition-prefixes "opencode-pi-widget" '("opencode-pi-widget-"))


;;; Generated autoloads from opencode-pipeline-core.el

(autoload 'opencode-pipeline-stage-buffer "opencode-pipeline-core" "\
Return STAGE's live chat buffer, or nil.
STAGE must be an execution-specific `opencode-pipeline-node'.  This helper
never creates or displays a buffer.

(fn STAGE)")
(register-definition-prefixes "opencode-pipeline-core" '("opencode-pipeline-"))


;;; Generated autoloads from opencode-pipeline-debug.el

(autoload 'opencode-pipeline-show-debug-log "opencode-pipeline-debug" "\
Display PIPELINE's debug buffer.
PIPELINE must have been started with :debug non-nil.

(fn PIPELINE)" t)
(register-definition-prefixes "opencode-pipeline-debug" '("opencode-pipeline--debug"))


;;; Generated autoloads from opencode-pipeline-runtime.el


;;; Generated autoloads from opencode-pipeline-commands.el

(autoload 'opencode-pipeline-start "opencode-pipeline-commands" "\
Instantiate and start PIPELINE, returning its execution.
PIPELINE must be an `opencode-pipeline-node-template' struct.  INPUT is
exposed to node prompt functions.  TITLE names this execution and prefixes
every session title.  DIRECTORY selects the single project used by every node
session.  When DEBUG is non-nil, write lifecycle and transition details to a
per-execution debug buffer.  MAX-EXECUTIONS limits the total prompts sent when
it is a positive number; nil, zero, and negative values mean unlimited
execution.

(fn PIPELINE &key ID INPUT TITLE DIRECTORY DEBUG MAX-EXECUTIONS ORIGIN DEFAULT-AGENT DEFAULT-MODEL DEFAULT-VARIANT ON-CREATE-FUNCTIONS)" nil)
(autoload 'opencode-pipeline-stop "opencode-pipeline-commands" "\
Stop PIPELINE without deleting its sessions.
When ABORT is non-nil, also abort the current backend session.

(fn PIPELINE &key ABORT)" '((list (opencode-pipeline--read-execution) :abort current-prefix-arg)))
(autoload 'opencode-pipeline-reset "opencode-pipeline-commands" "\
Remove PIPELINE execution without deleting its sessions.

(fn PIPELINE)" t)
(register-definition-prefixes "opencode-pipeline-commands" '("opencode-pipeline-"))


;;; Generated autoloads from opencode-pipeline-runtime.el

(register-definition-prefixes "opencode-pipeline-runtime" '("opencode-pipeline-"))


;;; Generated autoloads from opencode-pipeline-ui.el

(autoload 'opencode-pipeline-describe "opencode-pipeline-ui" "\
Display runtime information for PIPELINE.
Interactively, choose from currently registered executions.

(fn PIPELINE)" t)
(register-definition-prefixes "opencode-pipeline-ui" '("opencode-pipeline-"))


;;; Generated autoloads from opencode-workflow.el

(autoload 'opencode-workflow-rerun "opencode-workflow" "\
Rerun a previously stored dynamic workflow." t)
(register-definition-prefixes "opencode-workflow" '("opencode-workflow-"))


;;; Generated autoloads from opencode-workflow-rpc.el

(autoload 'opencode-workflow-submit "opencode-workflow-rpc" "\
Submit unevaluated workflow SOURCE and return a JSON result string.
TITLE, INPUT, IDEMPOTENCY-KEY, SOURCE-SESSION-ID, SOURCE-MESSAGE-ID,
DIRECTORY, and AGENT are trusted metadata supplied by the bridge caller.

(fn SOURCE &key TITLE INPUT IDEMPOTENCY-KEY SOURCE-SESSION-ID SOURCE-MESSAGE-ID DIRECTORY AGENT)" nil)
(autoload 'opencode-workflow-status "opencode-workflow-rpc" "\
Return workflow execution ID status as a JSON string.

(fn ID)" nil)
(autoload 'opencode-workflow-stop "opencode-workflow-rpc" "\
Stop workflow execution ID and return a JSON string.
When ABORT is non-nil, also abort the current worker backend session.

(fn ID &key ABORT)" nil)
(register-definition-prefixes "opencode-workflow-rpc" '("opencode-workflow-"))


;;; Generated autoloads from opencode-workflow-bridge.el

(autoload 'opencode-workflow-bridge-start "opencode-workflow-bridge" "\
Ensure the Emacs workflow bridge file and heartbeat are active." t)
(autoload 'opencode-workflow-bridge-stop "opencode-workflow-bridge" "\
Stop the workflow bridge heartbeat and remove its file." t)
(register-definition-prefixes "opencode-workflow-bridge" '("opencode-workflow-"))


;;; Generated autoloads from opencode-server.el

(register-definition-prefixes "opencode-server" '("opencode-server-"))

;;; End of scraped data

(provide 'opencode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; opencode-autoloads.el ends here
